#package(default_visibility = ["//visibility:private"])
#
#cc_library(
#    name = "ttvd-scd",
#    testonly = True,
#    srcs = [
#        "BruteForce.cpp",
#        "HierarchicalGrid.cpp",
#        "Kdtree.cpp",
#        "LooseOctree.cpp",
#        "Octree.cpp",
#        "SortAndSweep.cpp",
#        "UniformGrid.cpp",
#    ],
#    hdrs = [
#        "Base.h",
#        "BruteForce.h",
#        "HierarchicalGrid.h",
#        "ISpatialCell.h",
#        "ISpatialObject.h",
#        "ISpatialStructure.h",
#        "Kdtree.h",
#        "LooseOctree.h",
#        "Octree.h",
#        "SortAndSweep.h",
#        "SphereObject.h",
#        "UniformGrid.h",
#        "Vector3.h",
#    ],
#    visibility = [
#        "//visibility:public",
#    ],
#    deps = [
#        "@boost//:thread",
#    ],
#    alwayslink = 1,
#)
#
#cc_library(
#    name = "ph-ttvd",
#    testonly = True,
#    hdrs = [
#        "ph-kdtree.h",
#    ],
#    visibility = [
#        "//visibility:public",
#    ],
#    deps = [
#        "@phtree",
#    ],
#    alwayslink = 1,
#)
