package(default_visibility = ["//visibility:private"])

cc_test(
    name = "mcxme_d_test",
    timeout = "long",
    srcs = [
        "mcxme_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/mcxme:ph-mcxme",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "mcxme_box_d_test",
    timeout = "long",
    srcs = [
        "mcxme_box_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/mcxme:ph-mcxme",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "bbtree_multimap_d_test",
    timeout = "long",
    srcs = [
        "bbtree_multimap_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/bb-tree:ph-bb-tree",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "boost_rtree_multimap_d_test",
    timeout = "long",
    srcs = [
        "boost_rtree_multimap_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/boost:ph-boost-mm",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "boost_rtree_multimap_box_d_test",
    timeout = "long",
    srcs = [
        "boost_rtree_multimap_box_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/boost:ph-boost-mm",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "flann_kd_tree_d_test",
    timeout = "long",
    srcs = [
        "flann_kd_tree_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/flann:ph-flann",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "lsi_rtree_multimap_d_test",
    timeout = "long",
    srcs = [
        "lsi_rtree_multimap_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/lsi:ph-lsi-mm",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "lsi_rtree_multimap_box_d_test",
    timeout = "long",
    srcs = [
        "lsi_rtree_multimap_box_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/lsi:ph-lsi-mm",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

#cc_test(
#    name = "pcl_kd_tree_d_test",
#    timeout = "long",
#    srcs = [
#        "pcl_kd_tree_d_test.cc",
#    ],
#    linkstatic = True,
#    deps = [
#        "//src/pcl:ph-pcl",
#        "@gtest//:gtest_main",
#        "@pcl//:common",
#        "@phtree",
#    ],
#)

cc_test(
    name = "tinspin_kd_tree_d_test",
    timeout = "long",
    srcs = [
        "tinspin_kd_tree_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/tinspin",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)

cc_test(
    name = "tinspin_quadtree_d_test",
    timeout = "long",
    srcs = [
        "tinspin_quadtree_d_test.cc",
    ],
    linkstatic = True,
    deps = [
        "//src/tinspin",
        "@gtest//:gtest_main",
        "@phtree",
    ],
)
