package(default_visibility = ["//visibility:private"])

#cc_library(
#    name = "pcl-kd",
#    testonly = True,
#    hdrs = [
#        "pcl/kdtree/impl/io.hpp",
#        "pcl/kdtree/impl/kdtree_flann.hpp",
#        "pcl/kdtree/io.h",
#        "pcl/kdtree/kdtree.h",
#        "pcl/kdtree/kdtree_flann.h",
#    ],
#    visibility = [
#        "//visibility:public",
#    ],
#    deps = [
#    ],
#    alwayslink = 1,
#)
#
#cc_library(
#    name = "pcl-oct",
#    testonly = True,
#    hdrs = [
#        "pcl/octree/octree.h",
#    ],
#    visibility = [
#        "//visibility:public",
#    ],
#    deps = [
#    ],
#    alwayslink = 1,
#)
#
#cc_library(
#    name = "ph-pcl-include",
#    testonly = True,
#    hdrs = [
#        "bb_multimap.h",
#    ],
#    visibility = [
#        "//visibility:public",
#    ],
#    deps = [
#        ":pcl-kd",
#        ":pcl-oct",
#        "@phtree",
#    ],
#    alwayslink = 1,
#)
