module(
    name = "phtree-cpp-perf",
    version = "1.6.2",
)

# Bazel rules repositories.
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "rules_cc", version = "0.2.16")
bazel_dep(name = "platforms", version = "1.0.0")

# Dependencies.
bazel_dep(name = "googletest", version = "1.17.0.bcr.2")
bazel_dep(name = "spdlog", version = "1.17.0")
bazel_dep(name = "google_benchmark", version = "1.9.5")
bazel_dep(name = "boost.geometry", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.thread", version = "1.90.0.bcr.1")
#bazel_dep(name = "boost", version = "1.90.0.bcr.1")
bazel_dep(name = "pcl", version = "1.15.1.bcr.3")

# TODO update?
bazel_dep(name = "abseil-cpp", version = "20211102.0")

# Development environment tooling
http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_file = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_file")

http_archive(
  name = "lib-spatial-index",
  url = "https://github.com/libspatialindex/libspatialindex/archive/refs/tags/1.9.3.tar.gz",
  sha256 = "7b44340a3edc55c11abfc453bb60f148b29f569cef9e1148583e76132e9c7379",
  strip_prefix = "libspatialindex-1.9.3",
  build_file = "@//:third_party/lib-spatial-index.BUILD",
)

#http_archive(
#    name = "phtree",
#    integrity = "sha256-XbGxBmGbbgqv9IGMJPuUhOP/MgjOrjl96CYjEWQj1N8=",
#    strip_prefix = "phtree-cpp-1.6.2",
#    url = "https://github.com/tzaeschke/phtree-cpp/archive/refs/tags/v1.6.2.tar.gz",
#)

#git_repository(
#    name = "phtree",
#    branch = "main",
##    commit = "8822dbd367eee7e3904d824b780b99009a4a9915",
#    remote = "https://github.com/tzaeschke/phtree-cpp",
#)

local_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:local.bzl", "local_repository")
local_repository(
    name = "phtree",
    path = "/home/franky/work/phtree-cpp",
)

# Development environment tooling

BUILDIFIER_VERSION = "0.29.0"

http_file(
    name = "buildifier_linux",
    executable = True,
    sha256 = "4c985c883eafdde9c0e8cf3c8595b8bfdf32e77571c369bf8ddae83b042028d6",
    urls = ["https://github.com/bazelbuild/buildtools/releases/download/{version}/buildifier".format(version = BUILDIFIER_VERSION)],
)

http_file(
    name = "buildifier_macos",
    executable = True,
    sha256 = "9b108decaa9a624fbac65285e529994088c5d15fecc1a30866afc03a48619245",
    urls = ["https://github.com/bazelbuild/buildtools/releases/download/{version}/buildifier.mac".format(version = BUILDIFIER_VERSION)],
)

http_file(
    name = "buildifier_windows",
    executable = True,
    sha256 = "dc5d6ed5e3e0dbe9955f7606939c627af5a2be7f9bdd8814e77a22109164394f",
    urls = ["https://github.com/bazelbuild/buildtools/releases/download/{version}/buildifier.exe".format(version = BUILDIFIER_VERSION)],
)

http_archive(
    name = "bazel_compilation_database",
    sha256 = "bb1b812396e2ee36a50a13b03ae6833173ce643e8a4bd50731067d0b4e5c6e86",
    strip_prefix = "bazel-compilation-database-0.3.5",
    url = "https://github.com/grailbio/bazel-compilation-database/archive/0.3.5.tar.gz",
)
