load("@rules_cc//cc:defs.bzl", "cc_library")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "ph-util",
    testonly = True,
    hdrs = [
        "ph-util.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    alwayslink = 1,
)
