package(default_visibility = ["//visibility:private"])

cc_library(
    name = "ph-util",
    testonly = True,
    hdrs = [
        "ph-util.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    alwayslink = 1,
)
