package(default_visibility = ["//visibility:private"])

cc_library(
    name = "tinspin",
    testonly = True,
    hdrs = [
        "kdtree.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@phtree",
    ],
    alwayslink = 1,
)
