package(default_visibility = ["//visibility:private"])

cc_library(
    name = "robin_hood",
    testonly = True,
    hdrs = [
        "robin_hood.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
    ],
    alwayslink = 1,
)
