load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

package(default_visibility = ["//visibility:private"])

cc_library(
    name = "robin_hood",
    testonly = True,
    hdrs = [
        "robin_hood.h",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
    ],
    alwayslink = 1,
)
